[package]
name = "aoc2020-04"
version = "0.1.0"
authors = ["David Govea <govea.d@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc2020 = { path = ".." }
lazy_static = "1"
maplit = "1"
regex = "1"